/* config.h. Generated by cmake from config.h.cmake */

/****************************/

#cmakedefine HAVE_GNUC_VARARGS 1

#cmakedefine DBUS_CONSOLE_AUTH_DIR "@DBUS_CONSOLE_AUTH_DIR@"

#cmakedefine DBUS_SYSTEM_CONFIG_FILE  "@DBUS_SYSTEM_CONFIG_FILE@"
#cmakedefine DBUS_SESSION_CONFIG_FILE "@DBUS_SESSION_CONFIG_FILE@"
#cmakedefine DAEMON_NAME "@DAEMON_NAME@"
#cmakedefine DBUS_SYSTEM_BUS_DEFAULT_ADDRESS  "@DBUS_SYSTEM_BUS_DEFAULT_ADDRESS@"
#cmakedefine DBUS_SESSION_BUS_DEFAULT_ADDRESS "@DBUS_SESSION_BUS_DEFAULT_ADDRESS@"
#cmakedefine PACKAGE "@PACKAGE@"
#cmakedefine VERSION "@VERSION@"

/* Some dbus features */
#cmakedefine DBUS_BUILD_TESTS 1
#cmakedefine DBUS_BUS_ENABLE_DNOTIFY_ON_LINUX 1
#cmakedefine DBUS_DISABLE_ASSERTS 1
#cmakedefine DBUS_ENABLE_VERBOSE_MODE 1

/* Define to 1 if you have grp.h */
#cmakedefine   HAVE_GRP_H 1

/* Define to 1 if you have unistd.h */
#cmakedefine   HAVE_UNISTD_H 1

/* Define to 1 if you have sys/poll.h */
#cmakedefine    HAVE_POLL 1

/* Define to 1 if you have writev */
#cmakedefine   HAVE_WRITEV 1

#if defined(_WIN32) || defined(_WIN64)
#define DBUS_WIN
#endif

#ifndef _MSC_VER
#define uid_t int
#define gid_t int
#else
#define snprintf _snprintf
#define strtoll _strtoi64
#define strtoull _strtoui64
#endif

#ifdef interface
#undef interface
#endif

#ifndef SIGHUP
#define SIGHUP	1
#endif
